### PR TITLE
Check mutation type against tree

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR sets `mutType` intelligently according to what mutations are available on the tree. Furthermore, it allows nuc-genotype colorBy values for datasets lacking gene annotations in the metadata JSON. 

Tested against a number of datasets with no regressions seen, but @emmahodcroft please try on a few more! ~Please note that any d3-transition errors encountered are unrelated to this -- see #708.~ Update: Rebased onto v1.36.1 so that there should be no install / d3-related errors.

@tsibley may care to examine d34c075.

### CODE REVIEW

**Comment by tsibley** [comment]
@jameshadfield Thanks for these fixes! I'm not sure I see where the default `geneLength` passed to `decodeColorByGenotype` is `{}`. Can you point that out to me?

It seems like at the very least there should be a `nuc` key in any `geneLength` passed to `decodeColorByGenotype`?

**Comment by jameshadfield** [comment]
>I'm not sure I see where the default `geneLength` passed to `decodeColorByGenotype` is `{}`. Can you point that out to me?
https://github.com/nextstrain/auspice/blob/master/src/reducers/controls.js#L38

>It seems like at the very least there should be a `nuc` key in any `geneLength` passed to `decodeColorByGenotype`?
Not if annotations aren't defined in the metadata json.

**Comment by tsibley** [comment]
> Not if annotations aren't defined in the metadata json.

Ah, I see. I was thinking auspice could/did compute the nucleotide length itself.

**Comment by trvrb** [comment]
I'm going to go ahead and merge this. Going on Emma's specific feature testing and I can't find any regressions.

**Pull request merged**
