### PR TITLE
Chop branches

### PR DESCRIPTION
**Pull request by rneher**
improvements to phylotree. should not have changed the API

### CODE REVIEW

**Comment by rneher** [comment]
fixes #167

**Comment by jameshadfield** [comment]
@rneher this code looks good to me

**Comment by jameshadfield** [comment]
image
It's still not 100% yet, but it's a massive improvement and should be much easier to tweak now that .branches holds both the stem and the T

**Comment by rneher** [comment]
should be fixed now, issue was that tree is drawn before branch thickness is set. I put a rather hacky delayed redraw to fix it.

**Pull request merged**
