### PR TITLE
Nextflu features

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR addresses points 1-4 of #502. As such, once merged, nextflu.org can redirect to nextstrain.org. The "Nice to have" features will be tackled next (separate PRs). The titer features will come after that (one day). 

### Points in depth:
1. Strain name search - partial matches (i.e. "auck" shows c. 4 genomes in the dropdown) don't result in a change in the tree as it wasn't working smoothly -- i.e. you had to wait for the tree to update while you were typing. Can revisit this at some point - maybe we can change the tip radius on the fly.  Selected strain appears in the info panel (top of screen) as well as the URL (i.e. you can restore the state to a single strain via the URL). 
2. Frequencies - live already.
3. AA mutations - working for every dataset - see the branch label dropdown menu in the sidebar. Only labels are shown where the descendent visible tips account for more than 5% of the total visible tips (same as nextflu). Clade labels are always displayed.
4. ColorBys: LBI & clade are live already (although the latter requires updated augur JSONs).

### Somewhat unrelated points
* The JSON processing on initial load has been shifted from the reducers to a single action - fewer dispatches, fewer potential bugs, faster code.

### CODE REVIEW

**Comment by rneher** [comment]
Thanks, James. Being able to focus on new auspice will be a big step forward. 
a few comments (in random order): 
 * branch labels would be better right justified on end of branch
 * label for frequencies are pretty small. 
 * could it be that legend colors are ascending rather than descending in frequency? Would be nice to have the most relevant colors first. 
 * shouldn't `Normalized data` for frequencies by default?
 * the time tree view, the vaccine cross shows up at its `first chosen` date. Maybe we should implement some sort of background shading or a horizontal bar when a particular vaccine was chosen and used:
  |---------XXX NH 2017/18 XXX
 * don't show the gender.
 * legend item numbering and rounding could be prettier. 
 * I thought we had the joining of parent T-bars and child node sorted out, but is there are kinks. Also, we should probably draw children first, parents later. 
 * when zooming into a clade, the truncated frequencies look weird. Not sure how this can be avoided, though. 
 * I think the flu folks would prefer `HA1`was default genotype coloring rather than `nucleotide`

**Comment by rneher** [comment]
Zooming into a clade and looking at normalized `HA1:92` frequencies gives me this;
image

**Comment by rneher** [comment]
nextflu show a clade averaged age instead of the age of the individual tips. makes for a visually more pleasing experience. when plotting actual age, probably good to make non-existent values grey rather than black.

**Comment by rneher** [comment]
nextflu's tooltips for branches can be quite handy (to look for mutations, titer drops, average ages, etc). currently nextstrain doesn't have this "on the fly" info. thoughts?

**Comment by rneher** [comment]
I was thinking smth like this for vaccine strains (in the background obviously, not covering up the tree)
image

**Comment by trvrb** [comment]
@rneher: Interesting take. I like the direction. I also wondered about making the dashed lines go down to the bottom of the page and then over so as not to occlude so much.

**Comment by rneher** [comment]
some visual that links the strain to the period it is used as a vaccine would be great...

**Comment by trvrb** [comment]
@jameshadfield: This is fantastic.

* Strain search UI is great. I can understand why the iterative filtering of the tree presented a challenge. I really like how the search only applies to visible tips. Though could we resize tip circle to be bigger when only a single strain is selected? It's being hard to pick out once selected.

* I agree with @rneher that right aligned AA branch labels would be better. This should also apply to clade labels.

* AA branch labels are proper size for flu, but appear overly large for Zika and mumps.

* The coloring issues are all in augur. 

@rneher:

>nextflu's tooltips for branches can be quite handy (to look for mutations, titer drops, average ages, etc). currently nextstrain doesn't have this "on the fly" info. thoughts?

The Nextstrain spec was only showing colorBy attributes for the active colorBy. I think this the best way to do this as otherwise there are too many things in the tooltip.

>shouldn't Normalized data for frequencies by default?

I'm torn. Zooming to a clade with genotype with raw data looks like:

freq

which I think fits nicely with my own expectations when subsetting the data.

_Actually... I think perhaps better to thread frequencies issues separately as they are not part of this PR, but deserve attention._

>could it be that legend colors are ascending rather than descending in frequency? Would be nice to have the most relevant colors first.

I believe this is https://github.com/nextstrain/auspice/issues/503

**Comment by jameshadfield** [comment]
Everything fixed or broken out into seperate issues.

**Comment by trvrb** [comment]
Excellent! Thanks so much James.

**Pull request merged**
