### PR TITLE
docs: Improve TSV examples

### PR DESCRIPTION
**Pull request by tsibley**
See commit messages.

### Related issue(s)

#1588, https://github.com/nextstrain/auspice/pull/1588#discussion_r1131738370

### Testing

- [x] [Preview](https://nextstrain--1638.org.readthedocs.build/projects/auspice/en/1638/advanced-functionality/drag-drop-csv-tsv.html#example) looks good
- [x] Checks pass

### CODE REVIEW

**Review by victorlin — APPROVED** [review]
Slick! I learn something new about Sphinx every time you make a PR. Looks like I should be referencing [Sphinx docs](https://www.sphinx-doc.org/) more, or just browsing it in general...

**Comment by tsibley** [comment]
@victorlin

> I learn something new about Sphinx every time you make a PR. Looks like I should be referencing [Sphinx docs](https://www.sphinx-doc.org/) more, or just browsing it in general...

:blush: \o/

Yeah, I think _browsing_ official docs, in addition to using them for reference and search, is really underrated. The main reason is that browsing lets you build a mental index of what's available (and what's not), which is very useful before the reference/search phase of doc usage. ([I'm not alone either](https://twitter.com/hillelogram/status/1529509327840722946).)

<p align="center">⁂ ⁂ ⁂ </p>

I'm going to wait a bit for @jameshadfield to chime in here since he had [previous thoughts on these examples](https://github.com/nextstrain/auspice/pull/1588#discussion_r1131738370).

**Review by jameshadfield — APPROVED** [review]
Aesthetics are much improved here. I advised against tables as I wanted to reinforce that these are just plain-old text files, but the download button probably achieves this.

**Comment by tsibley** [comment]
@jameshadfield Thanks for the :eyes:. Agreed good to reinforce these are plain text files! I think the download links maybe do that a _bit_ less than inlined verbatim blocks, but also think that the improved reading experience of table + download is probably worth it.

**Pull request merged**
