### PR TITLE
Build auspice documentation website (incomplete)

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR introduces a new documentation website, to be publicized with the v2 release. This PR is a request for high-level comments about the docs structure & flow.

This must be installed locally to test -- please follow the instructions here: https://github.com/nextstrain/auspice/tree/docs/docs-src

### CODE REVIEW

**Comment by jameshadfield** [comment]
[Review auspice docs website](https://trello.com/c/3cxdSsjJ/9-review-auspice-docs-website)

**Comment by joverlee521** [comment]
Looks good! A couple thoughts:
- Highlighting the link of the current page in the side bar so users don't get lost within the docs
- Enabling search function for the docs
- `Tutorial` is a little misleading header link, it makes me think it will teach me how to set up auspice
- This might just be my personal taste, but the footer is a little too big

**Comment by jameshadfield** [comment]
Some more comments from other sources:

@milcisin 
> One small thing, for the "how to read a phylogeny section" I might recommend we just link to ARTIC's page here: http://artic.network/how-to-read-a-tree.html

> I found this tutorial super easy to use and it's not necessary worth our time to rebuild the wheel. 

@kairstenfay 
- I like the "Interpreting the ..." stubs. I'm glad you thought of how people will want to know how to interpret the results :)
- There's an inconsistent lowercase/uppercase usage of auspice and nextstrain throughout the docs that stood out to me. I'd prefer always uppercase, but that's just me.
- I would suggest removing all usages of the word "simply". These things may feel simple to us, but we shouldn't assume the technical level of our audience.
- What is "frontmatter parsing"?
- I noticed a bit of redundancy between http://localhost:3000/auspice/narratives/introduction and http://localhost:3000/auspice/narratives/how-to-write
- The community-builds link on this page is broken and I'm not sure what it's supposed to be http://localhost:3000/auspice/auspice-us/introduction
- Inconsistent capitalization of top-level links in navigation on left-hand side

**Comment by jameshadfield** [comment]
Merged into branch v2 in preparation for release. Thanks to all who helped here!

**Pull request closed without merging**
