### PR TITLE
Add URL query for show all (branch) labels

### LINKED ISSUE #1573: ENH: Make more view settings a URL parameter for more reproducible views
I love the `show all` branch label switch

Would it be possible to add this as a URL parameter to make views more reproducible?

There are other view settings that would be great to add to URL parameters, can't think of an example right now but will add it to the issue once I come across one.

image

Also, I'd love to be able to set this switch to _on_ by default 🙃

### PR DESCRIPTION
**Pull request by jameshadfield**
Tested manually & via /narratives/test/simultaneous-tree-updates

Closes #1573

### CODE REVIEW

**Comment by jameshadfield** [comment]
The review-app appears to have been build ("-----> Launching... Released v5. https://auspice-feat-branch-lab-hdcfc5.herokuapp.com/ deployed to Heroku") however I see the following when loading that URL. I don't think this :bug: is the fault of this PR however
image

**Comment by joverlee521** [comment]
Huh, the review app works for me now. There must have been something weird on Heroku's side.

**Review by joverlee521 — APPROVED** [review]
LGTM!

I pushed up commits to update the docs for URL params.

**Comment by jameshadfield** [comment]
Thanks @joverlee521!

**Pull request merged**
