### PR TITLE
Replace `equalArrays` with `lodash.isEqual`

### PR DESCRIPTION
**Pull request by joverlee521**
### Description of proposed changes

The custom `equalArrays` function can raise an error when one of the provided arguments does not have a `length` property. Instead of updating the function, just replace with `lodash.isEqual` which DTRT.
    
### Related issue(s)

Fixes https://github.com/nextstrain/auspice/issues/1690

### Testing

- [x] Checks pass
- [x] Fixes the crashing issue for the fetch dataset in the [nextstrain.org test app](https://nextstrain-s-nextstrain-i1pajb.herokuapp.com/fetch/storage.googleapis.com/ucsc-gi-cdph-bigtree/CDPH_08_28_2021/CDPH-subtree-0.json)

[1]: https://github.com/nextstrain/auspice/blob/-/DEV_DOCS.md#test-on-downstream-repositories

### CODE REVIEW

**Review by jameshadfield — APPROVED** [review]
Changing to lodash's `isEqual` command does fix this, however the underlying bug is that `changeEntropyCdsSelection` should be a no-op if the entropy data isn't present, i.e.

**Review by jameshadfield — CHANGES_REQUESTED** [review]
Changing to lodash's `isEqual` command does fix this, however it also allows non-array arguments which is not the intention of the code. The underlying bug is that `changeEntropyCdsSelection` should be a no-op if the entropy data isn't present, i.e.


```diff
--- a/src/actions/entropy.js
+++ b/src/actions/entropy.js
@@ -55,6 +55,7 @@ export const updateEntropyVisibility = debounce((dispatch, getState) => {
 export const changeEntropyCdsSelection = (arg) => (dispatch, getState) => {
   const action = {type: types.CHANGE_ENTROPY_CDS_SELECTION}
   const entropy = getState().entropy;
+  if (!entropy.loaded) return;
```

This is a good example of where TypeScript would have helped ensure arguments passed to `equalArrays` were indeed arrays, which was the intention of the code. We don't want cases where we pass two non-array-but-equal arguments to `isEqual`.

We should also improve `equalArrays` to catch cases where arguments are not arrays:

```
export const equalArrays = (a,b) => Array.isArray(a) && Array.isArray(b) && a.length===b.length && a.every((el, idx) => b[idx]===el);
```

I'll do a little more digging to see if there are other situations where we assume the presence of entropy data.

**Comment by joverlee521** [comment]
> While the intention of the code was to never call equalArrays with non-array arguments, we should also improve equalArrays to catch cases where we didn't do the right thing

```
export const equalArrays = (a,b) => Array.isArray(a) && Array.isArray(b) && a.length===b.length && a.every((el, idx) => b[idx]===el);
```

Hmm, this means it will return False if either arg is not an array and when the arrays are not equal which can make falsy checks problematic 
https://github.com/nextstrain/auspice/blob/cdf9f7c10508186d34a21d0c2341d9ad27d2f95a/src/components/entropy/index.js#L231-L232

I think it would be safer to do type checks separately than equality checks.

**Review by jameshadfield — APPROVED** [review]
> Hmm, this means it will return False if either arg is not an array and when the arrays are not equal which can make falsy checks problematic

Yes, that's fair, although `isEqual` will do the same. I think typescript is the way to go here, but that's well out of scope for this fix.

**Pull request merged**
