### PR TITLE
Styles update

### LINKED ISSUE #274: Sidebar collapse arrow gets smooth transition rather than snapto

### PR DESCRIPTION
**Pull request by trvrb**
This PR addresses several smaller styles issues. Final look is very similar to what we have now:

final-look

1. It darkens the background very slightly and adds a more even drop shadow to cards. I definitely prefer this. 

*Before*:

before-1

*After*:

after-1

2. It fixes the persistent issue with cards being slightly too short on their right-hand sides. Gutters are now equal to left and right of cards and stay the same width after opening and closing sidebar. **Ideally, this needs to be tested on Windows and Linux, Max scrollbars are weird.**

3. The sidebar toggle is now properly affixed to top of screen, so that when sidebar is scrolled it stays put.

4. The sidebar toggle is now place _over_ the sidebar scrollbar. There had been a persistent issue where you couldn't click the toggle after scrolling.

5. The sidebar toggle now properly animates with the rest of the sidebar when opening and closing.

6. Sidebar behavior is improved in mobile so that cards slide left and right rather than compressing to a thin strip. It feels much better in practice.

----------------------------

Note that commit bf7d040d60ed8b2c1c7525204abac2e0c92422cf experiments with a fixed titlebar per issue #209, like so:

fixed-titlebar

I decided that I very much preferred the white background titlebar and just making the sidebar toggle fixed. But please speak up if you'd prefer the fixed titlebar. (I tried fixed titlebar and white and it really didn't work):

white-background

----------------------------

Resolves #274

### CODE REVIEW

**Comment by colinmegill** [comment]
💯 - pronounced cards are better, and also prefer white background at the
top.

**Comment by trvrb** [comment]
I'm getting the same scrollbar behavior on Mac with "Show scrollbars" set to "Always" on Mac as I am with PC using both Chrome and Edge browsers. This is slightly non-ideal (in that the right hand edge of card is slightly cut-off). Attempting a fix.

**Comment by rneher** [comment]
this looks good on ubuntu firefox. Definitely improved!

**Comment by trvrb** [comment]
So, I finally figured out how to dynamically determine scrollbar widths:

https://github.com/nextstrain/auspice/commit/6e2176491877ce4cada64f9d2774469b027a1a1a#diff-c351b41538f669c947418a391312c738R43

I tested and this works beautifully (giving consistent gutters) in Mac OS Chrome, Firefox and Safari (with and without always visible scrollbars). It also works perfectly on PC Chrome and Edge browsers. Also works on iOS mobile. I'm going to declare this resolved.

Merging now.

**Pull request merged**
