### PR TITLE
color value was in quotes, was bad syntax. tested by making it #3f3 b…

### LINKED ISSUE #1081: invalid css (minor)
**Current Behavior**   
chrome 'inspect' shows invalid css.
In Elements tab, click on the <body class= .. > line
In styles, scroll to the bottom and find 'color: "#333"; '

**Expected behavior**  
No invalid css

**Possible solution**  
please assign to me, I have the fix

**Your environment: if running Nextstrain locally**  
 - Operating system:   Ubuntu
 - Browser:  Chrome
 - Version (e.g. `auspice 2.7.0`):  Master today

**Additional context**  

Hi all, 
this is very minor. please feel free to ignore it.
thanks
Rick

### PR DESCRIPTION
**Pull request by rleir**
…right lime green temporarily.

### Description of proposed changes    
What is the goal of this pull request? What does this pull request change?
Fix invalid CSS detected by a linter. My goal is mainly to clean all the minor lint warnings so the linter becomes useful again.

### Related issue(s)  

Fixes #1081 
Related to #  

### Testing
What steps should be taken to test the changes you've proposed?  
I tested by setting the color value to 3f3 bright lime green temporarily. It only affects the entropy scale lines and the text 'This work is made possible by the open...'. It would probably have historically colored most of the text in the UI. When it was not working someone corrected the color by creating 'darkgrey' or similar.

If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?  
No change to the tests but I can do if you would like me to.

### CODE REVIEW

**Comment by rleir** [comment]
Hi James, @jameshadfield 
This color value controls text color in few places on the display as noted: the scale lines and some text towards the bottom of the page. The 010101 value was chosen so there would be no change to what is displayed, so we would pass the integration tests. It is also marginally better for contrast, though the difference is hard to detect visually. Which would you like, 333 or 010101? Or we could remove the line completely from the CSS and pass all tests, with no visual difference. I will change it to #333 as requested, and we will have to update the integration test. I will do it tomorrow unless told otherwise.
The original design intent seems to be to control text color centrally for the whole app. If we had time on our hands we could remove other text color settings throughout the app, and control all text color from this one line. 
thanks -- Rick

**Comment by jameshadfield** [comment]
(The Integration tests most probably don't cover the footer text yet)

**Comment by rleir** [comment]
Agreed, let's remove it. I will make the change in the PR when I get a moment.

**Comment by rleir** [comment]
Hi James @jameshadfield To pass the integration test, your options are color: #010101 or remove this attribute completely here as has been done.  Now moving on to more important issues (suggestions please?)
Thanks
Rick

**Pull request merged**
