### PR TITLE
Intro paragraph

### PR DESCRIPTION
**Pull request by jameshadfield**
image

### CODE REVIEW

**Comment by trvrb** [comment]
Thanks for this @jameshadfield. However, the current behavior is confusing. We have, for example:

>Showing 76 of 379 genomes. Data from [[Metsky et al Zika Virus Evolution And Spread In The Americas (n=76)]]. n(Country): 32. n(Region): 6. Data sampled between October 2011 & April 2017.

This makes it seem like the Metsky et al data (currently shown) is from 32 countries. After thinking about this for a while, I came up with the following spec that solves this issue:

--------------------------

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017.

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017. Showing 76 sequences from [[Metsky et al Zika Virus Evolution And Spread In The Americas (n=76)]].

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017. Showing 28 sequences from [[Colombia (n=28)]].

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017. Showing 46 sequences from [[Colombia (n=28)]] [[Haiti (n=18)]].

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017. Showing 4 sequences from [[Metsky et al Zika Virus Evolution And Spread In The Americas (n=76)]] and from [[Colombia (n=28)]].

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017. Showing 4 sequences from [[Metsky et al Zika Virus Evolution And Spread In The Americas (n=76)]], from [[Colombia (n=28)]] and from [[South America (n=236)]].

Dataset of 379 sequences, from 35 authors, in 68 countries, in 3 regions, between May 2015 and Apr 2017. Showing 119 sequences between [[Jul 2016 and Apri 2017 (n=119)]].

**Comment by trvrb** [comment]
After playing around with sentence structure, I think that this is the better spec:

---------------------------------------

>Showing 379 of 379 sequences, from 35 authors, in 68 countries, in 3 regions, dated May 2015 to Apr 2017.

>Showing 76 of 379 sequences, from 1 author, 10 countries and 2 regions, dated Mar 2016 to Oct 2016. Filtered to [[Metsky et al Zika Virus Evolution And Spread In The Americas (76)]].

>Showing 28 of 379 sequences, from 3 authors, 1 country and 1 region, dated Oct 2015 to Dec 2016. Filtered to [[Colombia (28)]].

>Showing 46 of 379 sequences, from 5 authors, 2 countries and 2 regions, dated Oct 2015 to Dec 2016. Filtered to [[Colombia (28)]], [[Haiti (18)]].

>Showing 4 of 379 sequences, from 1 author, 1 country and 1 region, dated Apr 2016 to Jun 2016. Filtered to [[Metsky et al Zika Virus Evolution And Spread In The Americas (76)]], [[Colombia (28)]].

>Showing 0 of 379 sequences, from 0 authors, in 0 countries, in 0 regions. Filtered to [[Faria et al Establishment And Cryptic Transmission Of Zika Virus In Brazil And The Americas (n=40)]], [[USA (62)]].

**Comment by jameshadfield** [comment]
@trvrb please check if this is as you envisaged.
Note that the numbers in the footer are not updated like the header, as it makes no sense to display `n=0` for all the non selected countries (for instance)

**Comment by trvrb** [comment]
@jameshadfield ---

This is excellent. Really nice work here. I have only one small suggestion. Make the *n* the same in the filters at the top as it currently is in the filters at the bottom. It makes the most sense to me to have *n* be the total number in the particular filter. Not the intersection. So for example:

filters

would still say "Showing 16 of 379 genomes..." but it would say "Filtered to [[Metsky et al, Zika Virus Evolution And Spread In The Americas (n=76)]] [[Brazil (83)]]."

**Comment by jameshadfield** [comment]
ok. That's been added now. Each way has pros and cons.

image

**Comment by jameshadfield** [comment]
this PR closes #465

**Comment by trvrb** [comment]
I swapped "October" for "Oct" to give less bounciness when dragging date slider. I'm happy with this now.

**Comment by trvrb** [comment]
Thanks again for handling this @jameshadfield. Really nice work.

**Pull request merged**
