### PR TITLE
Branchlabels

### PR DESCRIPTION
**Pull request by rneher**

### CODE REVIEW

**Comment by trvrb** [comment]
I just tested this branch. There might be some small fiddling with placement, font size and amount of text to clip, but this seems generally great. There does seem to be an issue however, with how to interact these labels with +/– tree zoom. Right now these just size up, like branches. I don't think this should stop a merge however, as this is a general issue with tree zoom and will have to be addressed regardless of branch labels.

**Comment by rneher** [comment]
if this callback in treeview

https://github.com/nextstrain/auspice/blob/branchlabels/src/components/tree/treeView.js#L330

knows about the zoom level, this would be addressed.

**Comment by rneher** [comment]
padding etc is here:

https://github.com/nextstrain/auspice/blob/branchlabels/src/util/phyloTree.js#L154

can be also be set in the options dict on instantiation which overwrites defaults.

**Comment by trvrb** [comment]
Thanks @rneher. Great to put this in `setDefaults`. Would you agree on merging this now?

**Comment by rneher** [comment]
sure.

**Pull request merged**
