### PR TITLE
Hover on map deme will highlight tree tips

### PR DESCRIPTION
**Pull request by mapmeld**
My attempt at fixing #264 

> mousing over map demes should act just like mousing over legend items

The first commit does this now!

> The map demes should always represent geographical filters

The second commit modifies the clade-filtering so if you click a node on the map, you will see only nodes matching the location, and their parent branches. I didn't find this mode to be as helpful as expected, because the context is hidden? But the good news is, it works on both zika and ncov datasets (country or location attribute)

Screen Shot 2020-03-11 at 11 04 29 PM

### CODE REVIEW

**Comment by mapmeld** [comment]
I added a commit to support the datasets that I saw in the deploy.

- Adds support for "pie chart" maps (such as seasonal flu), separating map hover from legend hover
- Uses location, division, or country attribute in that order (for the ebola map).
- If you click a geo deme to filter, but no locations match, no filtering on the tree

**Comment by jameshadfield** [comment]
Thanks @mapmeld -- I'll try to test this out in the next couple of days!

**Comment by mapmeld** [comment]
Hi - I want to re-up this. Should I change clicking on a geo to use the same functionality as clicking on the geo filter links (Filter by Location, etc) further down the page?  I didn't notice them until later.

**Comment by mapmeld** [comment]
OK I've taken out the node click code, so this should contain hover code which works on /ncov-type nodes or /dengue-type pie charts

**Comment by jameshadfield** [comment]
Thanks @mapmeld, this is a really nice feature we've wanted for a long time!

I added 2 commits on top of this PR:
1. dc91b9f43d416791ac7c0b04892118c10291aad2 - Updates the algorithm to use `geoResolution` so we can check the corresponding value on all tips and match against the value of the hovered deme
2. ef81d51ab60c82ff8b94fcdc49c63eb62756a176 - remove map deme cursor=pointer which was left over from a version of the PR which had click behavior

**Pull request merged**
