### PR TITLE
this fixes (papers over) issue #547. 

### PR DESCRIPTION
**Pull request by rneher**
The issue was missing coordinates which result in missing transmissions from the index, which later results in 'type undefined' errors. This PR just sets lat/long to 0.0 instead. This will result in silly locations, but at least it doesn't break. This is a more general issue as to what should happen with incomplete geo-info.

### CODE REVIEW

**Comment by jameshadfield** [comment]
Hey @rneher -- could you run these JSONs through `augur validate <JSONs>` -- i'm interested if we pick up that they are "invalid". 

I'm happy enough with a temporary solution to stop things crashing, but this is a deeper seated issue in the design of the map component which assumes that every value has a corresponding lat-long. I guess we should (a) not show links to and from "unknown" demes (unknown in the sense that their lat/long is unknown) and (b) display an error to the user.

**Comment by jameshadfield** [comment]
Thanks... i'll fix `export` ASAP as this should definitely be an error. The issue of how Auspice should deal with "invalid" JSONs is a thorny one...

**Comment by rneher** [comment]
note that these were the ancient jsons that caused this issue back in May. Don't even know where they came from, you posted them on slack. My main motivation was to shorten the long issue list of auspice.

**Comment by trvrb** [comment]
I'm in favor of merging this. Having lots of redundancy in auspice seems like the way to go. Even if these JSONs won't validate, still better to have auspice not crash.

**Comment by trvrb** [comment]
I see. I'm agnostic in this case.

**Comment by rneher** [comment]
I tend to agree that not displaying them is better than drawing to some place in the Atlantic. But it is difficult for the user to know that smth is amiss if only a few lines are missing. My main reason to go back to this was to figure out where exactly this goes wrong for what reason. We had previously just caught it right before drawing. The root cause is info in the meta_json and that previously resulted in a corrupted the transmission data structure.

**Comment by jameshadfield** [comment]
Augur PR modifies `augur validate` to show the following when trying to validate these JSONs:

```
Validating that /Users/james/nextstrain/auspice/data/pater_meta.json and /Users/james/nextstrain/auspice/data/pater_tree.json are internally consistent...
	ERROR:  "vietnam", a value of the geographic resolution "country", appears in the tree but not in the metadata.
	ERROR:  	This will cause transmissions & demes involving this location not to be displayed in Auspice
	WARNING:  Color option "country", which contains a color_map, is missing "vietnam"
```

**Comment by jameshadfield** [comment]
Here's a possible fix (feel free to trash a1c66ac if it's not desired):

Demes/transmissions involving undefined lat/longs are not rendered & this error notification is shown on page load:

image

**Comment by jameshadfield** [comment]
@rneher @trvrb shall we merge this into master as currently stands?

**Comment by rneher** [comment]
My main reason to get back to this was to understand why this error happened and to reduce the number of `high priority bug` tags in the issue list. I think this is good to merge.

**Comment by jameshadfield** [comment]
Great!
Nice work on working out the root cause of this issue, and it's now well communicated in both auspice (via error notification box) and augur (via `augur validate`)

**Pull request merged**
