### PR TITLE
Improve ability to zoom out in the tree

### PR DESCRIPTION
**Pull request by jameshadfield**
See commit messages for details.

### CODE REVIEW

**Review by joverlee521 — COMMENTED** [review]
This works great! There's the added bonus of being able to zoom out after clicking the "zoom to selected" button as well! Previously this was not possible since the root branch was "inactivated" with the filter.

I updated the icon to be clear that the button is a "zoom out" button. I also added zoom out for the second tree. This means the zoom out button affects both trees, so if the user wants to zoom out of a specific tree they would have to use the old method of clicking the root branch. This pattern makes sense to me since the user already has to click on each tree individually in order to zoom in.

**Comment by joverlee521** [comment]
This should close #1348 and maybe #1390?

**Comment by trvrb** [comment]
This is great! Based on current behavior, I'd be supportive of merging. A couple brief thoughts however:
1. I had pictured the icon appearing over the root node when mousing over the tree. However, I really like having the icon in the row at the top, it makes it discoverable and not too in the way.
2. It slightly bugs me that the map zoom out is just a minus icon, while the tree zoom out is the magnifying glass minus icon. However, I would think just minus would be confusing and "zoom out" would take up too much space.

**Comment by emmahodcroft** [comment]
After playing with this a bit, I really like it! I agree with Trevor that I'd pictured the button differently but I actually find that position very neat and tidy and accessible.

**Comment by jameshadfield** [comment]
Thanks for the feedback and the improvements @joverlee521 - I think the icons can still be improved a bit in the future, but merging this now as it's immediately useful.

**Pull request merged**
