### PR TITLE
Jest test setup

### PR DESCRIPTION
**Pull request by tihuan**
To run the integration test:
1. Please make sure you have the zika dataset
2. Run `auspice view --datasetDir data` in one terminal tab
3. In another terminal tab, run `npm install && npm run integration-test`

You should get:

Screen Shot 2020-03-07 at 2 37 56 AM

4. If you wanna see the integration test in browser, you can run: `HEADLESS=false SLOWMO=10 npm run integration-test`

Please let me know if you encounter any issue 😄 Thank you!

### CODE REVIEW

**Comment by tihuan** [comment]
Rebased from `master`, no more merge conflicts :D PTAL again thank you!

**Comment by colinmegill** [comment]
LGTM!

**Comment by tihuan** [comment]
Awesome! Thanks so much, @colinmegill 😄 🎉 🚀 ! Who can merge this? Thank you!

**Comment by jameshadfield** [comment]
Thanks @tihuan -- this is being merged now. 

Due to current time constraints I don't have time currently to explore puppeteer in depth, but I am really looking forward to the work that can be done on top of this PR, relating to https://github.com/nextstrain/auspice/issues/917#issuecomment-596348566 and similar. @colinmegill has indicated that this PR is a good direction to go in.

**Comment by tihuan** [comment]
Thanks for the swift action, @jameshadfield ! Appreciate you merging the PR :D!

Yeah let's continue the discussion in https://github.com/nextstrain/auspice/issues/917 for the next steps!

**Pull request merged**
