### PR TITLE
Measurements URL query params

### PR DESCRIPTION
**Pull request by joverlee521**
## Description of proposed changes

Add URL query params for the measurements panel, see [docs for new query params](https://nextstrain--1848.org.readthedocs.build/projects/auspice/en/1848/advanced-functionality/view-settings.html#measurements-panel-url-query-options).
Examples using [community dataset](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17)

- [display collection that is not the default](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&m_collection=egg_HI_raw)
- [display raw data](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&m_display=raw)
- [group by serum](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&m_groupBy=serum)
- [hide overall mean](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&m_overallMean=hide)
- [hide threshold](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&m_threshold=hide)
- [filter to single reference strain](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&mf_reference_strain=A/Astrakhan/1/2011)
- [filter to two reference strains](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?d=measurements&mf_reference_strain=A/Astrakhan/1/2011&mf_reference_strain=A/Bayern/69/2009)

Also see new query params used in [example narrative](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/narratives/joverlee521/nextstrain-testing/test-multiple-dataset-measurements?n=3)

## Related issue(s)

Resolves https://github.com/nextstrain/auspice/issues/1815

## Checklist

- [x] Checks pass
- [ ] If making user-facing changes, add a message in [CHANGELOG.md](https://github.com/nextstrain/auspice/blob/HEAD/CHANGELOG.md) summarizing the changes in this PR
- [x] (to be done by a Nextstrain team member) [Create preview PRs on downstream repositories][1].

[1]: https://github.com/nextstrain/auspice/blob/-/DEV_DOCS.md#test-on-downstream-repositories

### CODE REVIEW

**Comment by joverlee521** [comment]
Hmm, just testing with a narrative locally and realizing that the state does not completely respect the URLs defined in the narrative slide because it preserves the existing state between slides. Will need to dig.

**Comment by joverlee521** [comment]
Hmm, looking into why the `m_collection` query is not working as expected in narratives.

**Review by huddlej — APPROVED** [review]
This worked really well for me in the test build, @joverlee521! I love the new docs and the new query field option names, too. Thank you!

The choice to implement multiple filter values as separate query string entries makes those filters unambiguous. I can see myself forgetting how this works initially and trying to use comma-delimited filter values like the other Auspice filters. For example, the following link works as expected with comma-delimited filters on the tree strains and separate query string keys for the reference strain filters:

https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?m_collection=egg_HI_raw&m_display=raw&m_overallMean=hide&mf_reference_strain=A/California/7/2009&mf_reference_strain=A/SouthAfrica/3626/2013&mf_source=NIMR-report-Feb2012&mf_source=NIMR-report-Sep2011&p=grid&s=A/California/7/2009,A/SouthAfrica/3626/2013

But this link does not work when I try to comma-delimit (probably not a real verb) the reference strain filters:

https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/joverlee521/nextstrain-testing/flu/seasonal/h1n1pdm/ha/09-17?m_collection=egg_HI_raw&m_display=raw&m_overallMean=hide&mf_reference_strain=A/California/7/2009,A/SouthAfrica/3626/2013&mf_source=NIMR-report-Feb2012&mf_source=NIMR-report-Sep2011&p=grid&s=A/California/7/2009,A/SouthAfrica/3626/2013

This is a pretty minor issue, though. Barring any JS-related comments other folks have on this PR, I'd be happy to see this merged and released, so I can start using it for real.

**Comment by joverlee521** [comment]
@jameshadfield and I walked through the Redux state changes in person. 
It's a bit of a mess right now because of a few of reasons
1. deferred loading of the measurements JSON 
2. the ranking of state to use (url params > collection display defaults > app defaults)
3. narrative page changes with the same dataset but changes in URL params

I'm planning to merge this as-is tomorrow because it works and the new functionality would be immediately helpful for @huddlej. We can plan to revisit the internal workings on how the Redux state is initialized and managed later.

**Comment by joverlee521** [comment]
@jameshadfield also requested two additional test cases in narratives: 

1. Change coloring _and_ measurements display between slides to check if we run into D3 bug from multiple state changes. Changing [slide 5](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/narratives/joverlee521/nextstrain-testing/test-multiple-dataset-measurements?n=5) to slide 6 has no issue because the [SVG is redrawn](https://github.com/nextstrain/auspice/blob/30c60dbd8a3d31d572777c35f364a930105a14ea/src/components/measurements/index.js#L236-L243) when color changes. I don't think there's any other situation that would make multiple changes to the same SVG element. 
2. Change dataset _and_ measurements URL params between slides to verify that the Redux state is reset and used appropriately. Changing [slide 1](https://nextstrain-s-nextstrain-zlos8n.herokuapp.com/community/narratives/joverlee521/nextstrain-testing/test-multiple-dataset-measurements?n=1) to slide 2: The new dataset gets loaded with the new measurements data that uses the correct display dictated by the URL params.

**Comment by jameshadfield** [comment]
> walked through the Redux state changes in person.

Notes:

Prior to this work, we load and parse the main JSON and read URL queries all in one redux step (largely `createStateFromQueryOrJSONs`). Sidecar JSONs are loaded via subsequent actions and there are no URL queries affecting these - `loadMeasurements` is the relevant function here. This prioritises rendering of the tree, with the downside that a measurements panel flashes in a second later ([example](https://next.nextstrain.org/community/blab/measurements-panel/flu/seasonal/h3n2/ha)). Narrative slide changes (query changes and/or dataset changes) operate the same way. 

This PR parses measurements panel URL queries within `createStateFromQueryOrJSONs` (although the JSON hasn't yet been parsed), and then reads them from redux state in `loadMeasurements`. Narrative slide changes where the dataset does change are akin to loading a new page. Narrative slide changes where the dataset doesn't change (but query does) apply these changes to the measurements data within `createStateFromQueryOrJSONs` (via `getCollectionDefaultControl`), and this is where it feels like the separation isn't as clean as it could be.

We discussed two alternative approaches:
1. the measurement URL queries are read within `loadMeasurements`. This is a nicer separation of concerns however narrative slide changes where the dataset doesn't change complicate this, as we never call `loadMeasurements`. We also want to process all changes within the same action to avoid out-of-sync rendering when a slide changes.
2. waiting for the measurements JSON to be fetched and loading everything within `createStateFromQueryOrJSONs`. The downside here is additional complexity in that function. The upsides are rendering all panels simultaneously and making it easier to one day implement measurements queries which modify the tree.

**Pull request merged**
