### PR TITLE
dev: Update workflow which creates PRs for nextstrain.org to account for Auspice move there

### PR DESCRIPTION
**Pull request by tsibley**
Related-to: <https://github.com/nextstrain/nextstrain.org/pull/673>

### Testing

- [x] Checks pass
- [ ] (to be done by a Nextstrain team member) [Create preview PRs on downstream repositories][1].

[1]: https://github.com/nextstrain/auspice/blob/-/DEV_DOCS.md#test-on-downstream-repositories

### CODE REVIEW

**Review by victorlin — APPROVED** [review]

**Comment by tsibley** [comment]
I started a [test run](https://github.com/nextstrain/auspice/actions/runs/4641468203/jobs/8214472239) for this PR and it worked, but took 15 minutes to `npm install nextstrain/auspice#$sha`. I can repro this locally with any install of Auspice from git (instead of the NPM registry). `npm` pegs more than one CPU and chews thru memory. Was this always the case?

**Comment by tsibley** [comment]
Looks like it:

image

Jeez. I guess it's fine though.

**Comment by victorlin** [comment]
@tsibley yeah, I noticed this a while back. I did some digging and this GitHub issue was the most informative: https://github.com/npm/cli/issues/4896

Looks like we're still using Node.js 14 / NPM 6 in the workflow. I'll make a PR to update it, since both downstream repos are using later versions now, and that should improve speed here based on the comments in the linked issue.

**Comment by tsibley** [comment]
@victorlin Ah, excellent! I did notice that the CI logs warn about using NPM 6 when Auspice declares compat with, at minimum, NPM 7.

**Pull request merged**
