### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by jameshadfield**
I think a PR is more appropriate than issue #306 

Note that no notifications are currently triggered from proper errors, and of course the buttons on the splash page should be removed.

### CODE REVIEW

**Comment by trvrb** [comment]
This is a fantastic direction @jameshadfield. I'm wondering however, if this isn't better discussed as the original issue #306 and then go with the PR when it's ready for code review. But perhaps the functionality is ready to go in even if no notifications are triggered as of yet?

**Comment by jameshadfield** [comment]
agreed!

**Comment by jameshadfield** [comment]
reopening as per @trvrb's request

**Comment by trvrb** [comment]
This is a good general direction. The notifications behave well, though I have to admit, I'm somewhat at a loss for when to exactly use these. Seems perhaps distracting to pop up a notification when switching datasets for example. I'm entirely sure though. The functionality seems good, just have to figure out the most appropriate use case.

**Pull request merged**
