### PR TITLE
936 tree zoom out

### PR DESCRIPTION
**Pull request by lukas-eu**
Solves 936

Zooming out one step when the root branch is clicked

As a visual cue for the user, the text in the bottom of the hover tooltip was changed for the root node
zoom_out

### CODE REVIEW

**Comment by jameshadfield** [comment]
Thanks @lukas-eu -- this is a great start, but polytomies (and branches with very small amounts of divergence or time) need to be taken into account as per #936 and via this gif 👇 cc @huddlej 

Mar-23-2020 12-12-38

**Comment by huddlej** [comment]
This is super cool, @lukas-eu! The relevant parts of [the original issue](https://github.com/nextstrain/auspice/issues/936) for dealing with polytomies are:

> Consider implementing one “step” based on the divergence view of the tree regardless of the currently selected branch length view. This implementation could be more biologically relevant and easier to actually implement in the existing tree component.

and

> Alternately, consider implementing one step as a delta of the existing branch length view (e.g., divergence of 1 or time of 1 month).

I think both of these suggestions would require potentially walking farther up the tree than the parent of the root node. For example, if following the divergence tree, I think you'd want to walk up to the first parent with a different divergence value than the root node.

**Comment by lukas-eu** [comment]
Hey, sorry I didn't fully get the desired behavior previously. I think this should fix it.
Divergence value float comparison is done with a tolerance value of 0.0001 https://github.com/nextstrain/auspice/pull/965/files#diff-7bc7fe459ddcc463b80cd9a73a6c05b0R114

**Comment by huddlej** [comment]
I think this is working much closer to how I had imagined. There is a weird edge case I noticed with the original example from the issue where zooming into the Washington hCoV-19 clade and back out again hides the first Washington sample that used to be visible.

zoom-issue

Do you think this could be related to the divergence tolerance value setting?

**Comment by huddlej** [comment]
@lukas-eu that last change fixed things! @jameshadfield does this work for your polytomy example, too? 

I noticed one regression at the bottom of the internal node tooltips (below). Is this maybe related to separate translation work?

image

**Comment by lukas-eu** [comment]
@huddlej Also my bad, messed that up when I was resolving merge conflicts with the master. 
Should be fixed with the next commit.

**Comment by jameshadfield** [comment]
Thanks @lukas-eu -- i've added a bit of work on top of this, which is now PR #1001. Would you mind taking a look at that?

**Pull request closed without merging**
