### PR TITLE
auspice extension architecture (do not merge)

### PR DESCRIPTION
**Pull request by jameshadfield**
This PR is my way of introducing the recent work moving auspice from a web-app to be used within nextstrain.org to a versatile node / javascript program which may be customized to have custom functionality and appearance.

It's best introduced via the docs -- https://github.com/nextstrain/auspice/tree/extend/docs -- which detail the commands on how to build auspice with or without extensions. The current collection of customised versions, together with docs on how to build them:

* Auspice.us -- http://auspice-us-dev.herokuapp.com -- [docs here](https://github.com/nextstrain/auspice/blob/extend/auspice.us/README.md)
* Serverless -- https://blab.github.io/ZEBOV -- [docs here](https://github.com/blab/ZEBOV)
* Nextstrain -- http://nextstrain-dev.herokuapp.com -- [docs here](https://github.com/nextstrain/nextstrain.org/blob/whitelabel/README.md)

[This issue](https://github.com/nextstrain/auspice/issues/680) is the to-do list for this PR.
Reasonably soon I think we can build the production nextstrain.org site off this branch, allowing it to be merged into master and more incremental PRs used. Note that this represents a decoupling of nextstrain & auspice: when we want to update the auspice code used in nextstrain.org we will (or travis will) rebuild the customised auspice code using an update version of auspice.

Constructive comments welcome. As noted in all the docs, the APIs / config architecture is very much in flux and not at all fixed.

### CODE REVIEW

**Comment by jameshadfield** [comment]
The (first iteration of the) documentation for this branch can be seen here: https://nextstrain.github.io/sandbox 
My plan is to serve this via github pages from the auspice repository (since the branch isn't merged into master we can't use github pages from the actual auspice repo, so i'm using a temporary repo in the meantime).

**Comment by tsibley** [comment]
Here are my thoughts on the dataset/server interface.

### Current

The Charon API, [as described in the white-labelling docs][api doc], relies on a dynamic server able to respond to the following endpoints:

    /charon/getAvailable
    /charon/getAvailable?prefix=flu_seasonal

    /charon/getDataset?prefix=flu_seasonal_h3n2_ha_2y
    /charon/getDataset?prefix=flu_seasonal_h3n2_ha_2y&type=tip-frequencies

    /charon/getNarrative?prefix=flu-report-2018-Q3.md

Pros:

* Server allows for custom logic to dynamically respond with different datasets for different people (e.g. logged in users).

Cons:

* Requires a dynamic server.

* Statically-hosted builds (e.g. for GitHub Pages) and S3-served builds (e.g. for Nextstrain) must be special-cased since no dynamic server is possible.

* Paths in the user-facing URL require transformation back and forth, which historically has been a source of bugs.

[api doc]: https://github.com/nextstrain/auspice/blob/extend/docs/charonAPI.md


### Proposed

My proposed "data API" is to use standard HTTP access for what it's good at by changing Auspice to request these URLs instead:

    /datasets.json
    /narratives.json

    /dataset/${datasetPath}/${type}.json
    /dataset/flu/seasonal/h3n2/ha/2y/{tree,meta,tip-frequencies}.json

    /narrative/${name}.json
    /narrative/flu-report/2018/Q3.md

Pros:

* Endpoints can be provided _either_

  - by a set of files on a static host (e.g. GitHub Pages, S3), _or_
  - by a dynamic server in order to customize responses for different people (e.g.  logged in users).

* Statically-hosted builds (e.g. for GitHub Pages) and S3-served builds (e.g. for Nextstrain) just work with no special-casing or additional server logic in Auspice.

* Paths in the user-facing URL match those behind the scenes without any transformation.

* Standard HTTP caching strategies work without a custom server complicating it.

Cons:

_I don't see any downsides to this approach, but maybe you do?  Looking for feedback!_

**Comment by jameshadfield** [comment]
@tsibley thanks for your proposal -- really appreciate someone looking at this code and the new API seems very promising to me.

I'm going to try to get this PR into master (for auspice & nextstrain.org) ASAP with the server API as it currently stands (since the code is all working now), then play around with this proposal in another branch.

**Comment by jameshadfield** [comment]
#680 is probably the auspice v2.0 release list -- for this PR i'm just going to add more to the docs content, fix the docs styling, add some more variables to the sidebar theme and tidy up the commits

**Pull request closed without merging**
