### PR TITLE
show amino acid mutations in tool tip

### LINKED ISSUE #303: mutation annotation
tool tips show nucleotide mutations instead of amino acid mutations as advertised. 
When coloring by genotype, the tooltips show smth like "gt-ns1-454: unknown".

### PR DESCRIPTION
**Pull request by rneher**
this fixes #303

### CODE REVIEW

**Comment by jameshadfield** [comment]
now online @ http://auspice-dev.herokuapp.com

will merge soon if there are no obbjections

**Comment by rneher** [comment]
looking good. thanks! Two quick suggestions: In the legend, I think I'd prefer "Genotype at position 3578" to "Genotype at nuc site 3578". In the tooltip, maybe "Nucleotide mutations:\n" is better than "Nt mutations:"?

**Comment by jameshadfield** [comment]
@rneher done and up on the dev site

Still unfixed problems here https://github.com/nextstrain/auspice/issues/300 but shouldn't stop this PR

**Comment by rneher** [comment]
thanks. happy for this to be merged.

**Pull request merged**
